project:
  type: book
  output-dir: _book

book:
  title: "tidyverse notes"
  author: "Jesse Sadler"

  chapters:
    - index.qmd

    - part: "tidyverse"
      chapters:
        - 01-pipe.qmd
        - 01-readr.qmd
        - 01-dplyr-colwise.qmd
        - 01-dplyr-rowwise.qmd
        - 01-dplyr-1.0.0.qmd
        - 01-dplyr-1.1.0.qmd
        - 01-forcats.qmd
        - 01-lubridate.qmd
        - 01-tidy-data.qmd
        - 01-tidyr-pivoting.qmd
        - 01-tidyr-rectangling.qmd
        - 01-purrr.qmd
    - part: "ggplot2"
      chapters:
        - 02-ggplot2-rstudioconf-2022.qmd
        - 02-geoms.qmd
        - 02-aesthetics.qmd
        - 02-annotations.qmd
        - 02-scales.qmd
        - 02-scales-color.qmd
        - 02-coords.qmd
        - 02-guides.qmd
        - 02-themes.qmd
        - 02-patchwork.qmd
    - part: "tidy eval"
      chapters:
        - 03-programming-dplyr-superceded.qmd
        - 03-programming-dplyr.qmd
        - 03-metaprogramming.qmd
        - 03-rlang-tidyeval.qmd
        - 03-rlang-metaprogramming.qmd
  appendices:
    - readr-data.qmd
    - references.qmd

bibliography: references.bib

# YAML
format:
  html:
    theme:
      - default
      - theme.scss
    toc: true
    code-link: true
    number-depth: 3
    highlight-style: arrow
