project:
  type: book
  output-dir: _book

book:
  title: "tidyverse notes"
  author: "Jesse Sadler"

  chapters:
    - index.qmd

    - part: "tidyverse"
      chapters:
        - 01-readr.qmd
        - 01-dplyr-colwise.qmd
        - 01-dplyr-rowwise.qmd
        - 01-dplyr-1.0.0.qmd
        - 01-dplyr-1.1.0.qmd
        - 01-forcats.qmd
        - 01-purrr.qmd
    - part: "tidy eval"
      chapters:
        - 02-programming-dplyr-superceded.qmd
        - 02-programming-dplyr.qmd
        - 02-metaprogramming.qmd
        - 02-rlang-tidyeval.qmd
        - 02-rlang-metaprogramming.qmd
  appendices:
    - readr-data.qmd
    - references.qmd

bibliography: references.bib

# YAML
format:
  html:
    theme:
      - default
      - theme.scss
    toc: true
    code-link: true
    number-depth: 3
    highlight-style: arrow
